import type { NextPage } from "next";
import Head from "next/head";
import { Button, Stack, Center, Space } from "@mantine/core";
import Quote from "../components/quote";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`Answer for your questions(not)`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Stack>
          <h1>Unanswered</h1>
          <Space />
          <Button>Answers</Button>
          <Space />

          <Quote />
        </Stack>
      </Center>
    </div>
  );
};

export default Home;
